<?php

    use App\Http\Controllers\PostController;
    
    $postController = new PostController();

    $posts = $postController->index();

    dd($posts);
?>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>
<div>ddddddddddd</div>