CREATE TABLE IF NOT EXISTS posts (
    id INT UNSIGNED AUTO_INCREMENT NOT NULL,
    author VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    created_at DATETIME NULL,
    PRIMARY KEY(id)
)
ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS users (
    id INT UNSIGNED AUTO_INCREMENT NOT NULL,
    firstanme VARCHAR(255) NOT NULL,
    lastanme VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    created_at DATETIME NULL,
    PRIMARY KEY(id)
)
ENGINE = INNODB;

ALTER TABLE users
ADD COLUMN password VARCHAR(255) NOT NULL;